"""
PixelTrace - Feature Schema
---------------------------
Defines the complete feature schema used by the ML pipeline.
"""

FEATURE_COLUMNS = [

    # Edge
    "edge_density",
    "edge_pixels",

    # FFT
    "fft_mean",
    "fft_std",
    "fft_max",
    "fft_radial_mean_0",
    "fft_radial_std_0",
    "fft_radial_mean_1",
    "fft_radial_std_1",
    "fft_radial_mean_2",
    "fft_radial_std_2",
    "fft_radial_mean_3",
    "fft_radial_std_3",
    "fft_radial_mean_4",
    "fft_radial_std_4",
    "fft_radial_mean_5",
    "fft_radial_std_5",
    "fft_radial_mean_6",
    "fft_radial_std_6",
    "fft_radial_mean_7",
    "fft_radial_std_7",
    "fft_radial_mean_8",
    "fft_radial_std_8",
    "fft_radial_mean_9",
    "fft_radial_std_9",
    "fft_angular_mean_0",
    "fft_angular_std_0",
    "fft_angular_mean_1",
    "fft_angular_std_1",
    "fft_angular_mean_2",
    "fft_angular_std_2",
    "fft_angular_mean_3",
    "fft_angular_std_3",
    "fft_angular_mean_4",
    "fft_angular_std_4",
    "fft_angular_mean_5",
    "fft_angular_std_5",
    "fft_angular_mean_6",
    "fft_angular_std_6",
    "fft_angular_mean_7",
    "fft_angular_std_7",

    # Texture
    "texture_mean",
    "texture_std",
    "texture_energy",
    "glcm_contrast",
    "glcm_homogeneity",
    "glcm_correlation",
    "texture_lbp_bin_0",
    "texture_lbp_bin_1",
    "texture_lbp_bin_2",
    "texture_lbp_bin_3",
    "texture_lbp_bin_4",
    "texture_lbp_bin_5",
    "texture_lbp_bin_6",
    "texture_lbp_bin_7",
    "texture_lbp_bin_8",
    "texture_lbp_bin_9",
    "texture_lbp_bin_10",
    "texture_lbp_bin_11",
    "texture_lbp_bin_12",
    "texture_lbp_bin_13",
    "texture_lbp_bin_14",
    "texture_lbp_bin_15",
    "texture_lbp_bin_16",
    "texture_lbp_bin_17",

    # Structural
    "gradient_mean",
    "gradient_std",
    "gradient_energy",
    "horizontal_ratio",
    "vertical_ratio",
    "diagonal_ratio",
    "orientation_entropy",
    "dominant_orientation",
    "hog_bin_0",
    "hog_bin_1",
    "hog_bin_2",
    "hog_bin_3",
    "hog_bin_4",
    "hog_bin_5",
    "hog_bin_6",
    "hog_bin_7",
    "hog_bin_8",

    # Reflection
    "reflection_ratio",
    "reflection_pixels",

    # Sharpness
    "sharpness_mean",
    "sharpness_variance",

    # Color
    "h_mean",
    "s_mean",
    "v_mean",
    "h_std",
    "s_std",
    "v_std",
    "corr_rg",
    "corr_gb",
    "corr_br",
    "lap_diff_rg",
    "lap_diff_gb",
    "lap_diff_br",
    "gray_skew",
    "gray_kurtosis",
    "sat_skew",
    "sat_kurtosis",

    # Geometry
    "contour_count",
    "largest_contour_area",
    "mean_contour_area",
    "aspect_ratio",

    # Noise
    "noise_mean",
    "noise_std",
    "noise_variance",
    "high_noise_ratio",
    "residual_energy",

    # Moiré / Pixel-Grid Frequency
    "moire_spectral_flatness",
    "moire_peak_count",
    "moire_peak_ratio",
    "moire_hf_ratio",
    "moire_lf_ratio",
    "moire_hf_to_lf",
    "moire_ring_cv",
    "moire_angular_entropy",
    "moire_angular_dominance",

    # Chromatic Aberration
    "ca_rg_alignment",
    "ca_gb_alignment",
    "ca_mean_alignment",
    "ca_edge_rg_diff",
    "ca_edge_gb_diff",
    "ca_edge_color_var",
    "ca_subpixel_h",
    "ca_subpixel_v",

    # CNN Features (32 components from current build — re-run build_embeddings for 128)
    "cnn_000",
    "cnn_001",
    "cnn_002",
    "cnn_003",
    "cnn_004",
    "cnn_005",
    "cnn_006",
    "cnn_007",
    "cnn_008",
    "cnn_009",
    "cnn_010",
    "cnn_011",
    "cnn_012",
    "cnn_013",
    "cnn_014",
    "cnn_015",
    "cnn_016",
    "cnn_017",
    "cnn_018",
    "cnn_019",
    "cnn_020",
    "cnn_021",
    "cnn_022",
    "cnn_023",
    "cnn_024",
    "cnn_025",
    "cnn_026",
    "cnn_027",
    "cnn_028",
    "cnn_029",
    "cnn_030",
    "cnn_031",
    "cnn_032",
    "cnn_033",
    "cnn_034",
    "cnn_035",
    "cnn_036",
    "cnn_037",
    "cnn_038",
    "cnn_039",
    "cnn_040",
    "cnn_041",
    "cnn_042",
    "cnn_043",
    "cnn_044",
    "cnn_045",
    "cnn_046",
    "cnn_047",
    "cnn_048",
    "cnn_049",
    "cnn_050",
    "cnn_051",
    "cnn_052",
    "cnn_053",
    "cnn_054",
    "cnn_055",
    "cnn_056",
    "cnn_057",
    "cnn_058",
    "cnn_059",
    "cnn_060",
    "cnn_061",
    "cnn_062",
    "cnn_063",
    "cnn_064",
    "cnn_065",
    "cnn_066",
    "cnn_067",
    "cnn_068",
    "cnn_069",
    "cnn_070",
    "cnn_071",
    "cnn_072",
    "cnn_073",
    "cnn_074",
    "cnn_075",
    "cnn_076",
    "cnn_077",
    "cnn_078",
    "cnn_079",
    "cnn_080",
    "cnn_081",
    "cnn_082",
    "cnn_083",
    "cnn_084",
    "cnn_085",
    "cnn_086",
    "cnn_087",
    "cnn_088",
    "cnn_089",
    "cnn_090",
    "cnn_091",
    "cnn_092",
    "cnn_093",
    "cnn_094",
    "cnn_095",
    "cnn_096",
    "cnn_097",
    "cnn_098",
    "cnn_099",
    "cnn_100",
    "cnn_101",
    "cnn_102",
    "cnn_103",
    "cnn_104",
    "cnn_105",
    "cnn_106",
    "cnn_107",
    "cnn_108",
    "cnn_109",
    "cnn_110",
    "cnn_111",
    "cnn_112",
    "cnn_113",
    "cnn_114",
    "cnn_115",
    "cnn_116",
    "cnn_117",
    "cnn_118",
    "cnn_119",
    "cnn_120",
    "cnn_121",
    "cnn_122",
    "cnn_123",
    "cnn_124",
    "cnn_125",
    "cnn_126",
    "cnn_127",

    # Label
    "label",
]